name: raonson
description: Instagram-style social app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7

  # Media
  image_picker: ^1.1.2
  video_player: ^2.9.2
  chewie: ^1.8.7

  # State
  provider: ^6.1.5+1

  # Utils
  uuid: ^4.5.2
  http: ^1.2.2
  intl: ^0.18.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
