name: raonson
description: Instagram-style social app with AI chat and KingAI
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.4.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  # Firebase
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.4

  # State
  provider: ^6.0.5

  # Media
  image_picker: ^1.0.4
  video_player: ^2.8.2   # ⬅️ МАХСУС поён карда шуд
  chewie: ^1.7.0

  # Utils
  http: ^1.1.0
  uuid: ^4.3.3
  shared_preferences: ^2.2.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
